[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Production context
[context.production]
  environment = { VITE_ENVIRONMENT = "production", VITE_ENABLE_MOCK_API = "false", VITE_ENABLE_REDUX_LOGGER = "false" }

# Deploy Preview context
[context.deploy-preview]
  environment = { VITE_ENVIRONMENT = "staging", VITE_ENABLE_MOCK_API = "false", VITE_ENABLE_REDUX_LOGGER = "false" }

# Branch Deploy context
[context.branch-deploy]
  environment = { VITE_ENVIRONMENT = "staging", VITE_ENABLE_MOCK_API = "false", VITE_ENABLE_REDUX_LOGGER = "false" }

# Specific branch context: Deploy from the "develop" branch with different configuration
[context.develop]
  environment = { VITE_ENVIRONMENT = "staging", VITE_ENABLE_MOCK_API = "false", VITE_ENABLE_REDUX_LOGGER = "false" }

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://analytics.geniusonlinenavigator.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://images.geniusonlinenavigator.com https://res.cloudinary.com; connect-src 'self' https://api.geniusonlinenavigator.com wss://api.geniusonlinenavigator.com; font-src 'self'; object-src 'none'; media-src 'self'; frame-src 'self'; worker-src 'self' blob:; manifest-src 'self'; base-uri 'self'; form-action 'self';"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Performance optimization
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Plugin configuration
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Environment variable configuration
[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  framework = "vite"
  autoLaunch = true
